kind: pipeline
type: docker
name: publish

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: restore-backend-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - /go-cache
        - /var/cache/apk
    volumes:
      - name: cache
        path: /cache
  - name: backend-build
    image: golang:1.19-alpine
    environment:
      GOCACHE: /go-cache
    commands:
      - apk add gcc g++ upx
      - go build -o main
    depends_on:
      - restore-backend-cache
  - name: rebuild-backend-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - /go-cache
        - /var/cache/apk
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - backend-build


  - name: restore-frontend-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./frontend/node_modules
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - submodules
  - name: frontend-build
    image: node:19-alpine
    commands:
      - cd frontend
      - node -v
      - yarn --version
      - yarn install && yarn build
    depends_on:
      - submodules
      - restore-frontend-cache
  - name: rebuild-frontend-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./frontend/node_modules
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - frontend-build

  - name: docker
    image: plugins/docker
    settings:
      registry: r.s8k.top
      username: docker
      password:
        from_secret: DOCKER_REGISTRY_PASSWD
      repo: r.s8k.top/valyria-dc
    depends_on:
      - backend-build
      - frontend-build

volumes:
  - name: cache
    host:
      path: /var/cache/drone-runner
