kind: pipeline
type: docker
name: publish

trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: restore-backend-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - /go
        - /root/.cache/go-build
    volumes:
      - name: go
        path: /go
      - name: go-build
        path: /root/.cache/go-build
      - name: cache
        path: /cache
  - name: backend-build
    image: r.s8k.top/golang-gcc
    pull: never
    commands:
      - go build -o main
      - upx main
    volumes:
      - name: go
        path: /go
      - name: go-build
        path: /root/.cache/go-build
      - name: cache
        path: /cache
    depends_on:
      - restore-backend-cache
  - name: rebuild-backend-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - /go
        - /root/.cache/go-build
    volumes:
      - name: cache
        path: /cache
      - name: go
        path: /go
      - name: go-build
        path: /root/.cache/go-build
    depends_on:
      - backend-build


  - name: restore-frontend-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./frontend/node_modules
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - submodules
  - name: frontend-build
    image: node:19-alpine
    commands:
      - cd frontend
      - node -v
      - yarn --version
      - yarn install && yarn build
    depends_on:
      - restore-frontend-cache
  - name: rebuild-frontend-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./frontend/node_modules
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - frontend-build

  - name: docker
    image: docker:dind
    environment:
      DOCKER_PASS:
        from_secret: DOCKER_REGISTRY_PASSWD
    commands:
      - docker login -u docker -p $DOCKER_PASS r.s8k.top
      - docker build -t r.s8k.top/valyria-dc .
      - docker push r.s8k.top/valyria-dc
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    depends_on:
      - backend-build
      - frontend-build

  - name: deploy
    image: plugins/webhook
    settings:
      method: POST
      urls: http://101.43.76.104:4000/api/services/valyria-dc/deploy
      headers:
        from_secret: S2_COMPOSE_DEPLOYER_SECRET_HEADER
    depends_on:
      - docker

volumes:
  - name: cache
    host:
      path: /var/cache/drone-runner
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: go
    temp: {}
  - name: go-build
    temp: {}
